//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace validationUsingAnnotation_Ex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emptbl
    {
        public long? empid { get; set; }
        public string empname { get; set; }
        public string address { get; set; }
        public string emailid { get; set; }
        public string mono { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<long> dept { get; set; }
    
        public virtual depttbl depttbl { get; set; }
    }
}
