//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace partialviewchildactioncall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customertbl
    {
        public long customerid { get; set; }
        public string customername { get; set; }
        public string address { get; set; }
        public string emailid { get; set; }
        public string mobileno { get; set; }
        public string proid { get; set; }
    }
}
