//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirstallquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillTbl()
        {
            this.paymenttbls = new HashSet<paymenttbl>();
        }
    
        public long billid { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<decimal> billamount { get; set; }
        public Nullable<long> customerid { get; set; }
    
        public virtual customertbl customertbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paymenttbl> paymenttbls { get; set; }
    }
}
