//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirstallquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymenttbl
    {
        public long paymentid { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public Nullable<decimal> paymenetamount { get; set; }
        public Nullable<long> billid { get; set; }
    
        public virtual BillTbl BillTbl { get; set; }
    }
}
