//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curdPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenttbl
    {
        public string studentname { get; set; }
        public long studentid { get; set; }
        public decimal marks { get; set; }
        public string address { get; set; }
        public string mobileno { get; set; }
        public string emailid { get; set; }
        public long studentdeptid { get; set; }
    
        public virtual studentdept studentdept { get; set; }
    }
}
