//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curdPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentdept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studentdept()
        {
            this.studenttbls = new HashSet<studenttbl>();
        }
    
        public long studentdeptid { get; set; }
        public string studentdeptname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studenttbl> studenttbls { get; set; }
    }
}
