// <auto-generated />
namespace code_first_exam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class publisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(publisher));
        
        string IMigrationMetadata.Id
        {
            get { return "202402241140244_publisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
