//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_authorization__filter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long productid { get; set; }
        public string productname { get; set; }
        public string mfgname { get; set; }
        public decimal price { get; set; }
    }
}
