//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_authorization__filter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertbl
    {
        public long userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailid { get; set; }
        public string mobileno { get; set; }
        public string password { get; set; }
        public string address { get; set; }
    }
}
