//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long payid { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public Nullable<decimal> payamout { get; set; }
        public Nullable<long> billid { get; set; }
    
        public virtual bill bill { get; set; }
    }
}
